ai:
  model: gpt-4
  provider: openai
  temperature: 0.1
  timeout: 30
logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
paths:
  results: results
  system_prompts: data/system_prompts
  tests: tests
  user_inputs: data/user_requirements
polar:
  cli_path: oso-cloud
  max_retry_attempts: 3
  validation_timeout: 30
storage:
  backend: local
  base_path: ./
